// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// reader
List reader(String go_file);
RcppExport SEXP _ontologyReader_reader(SEXP go_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type go_file(go_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(reader(go_file));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_ontology();

static const R_CallMethodDef CallEntries[] = {
    {"_ontologyReader_reader", (DL_FUNC) &_ontologyReader_reader, 1},
    {"_rcpp_module_boot_ontology", (DL_FUNC) &_rcpp_module_boot_ontology, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ontologyReader(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
