#' @useDynLib ontologyReader
#' @import R6
#' @importFrom Rdpack reprompt
#' @title ontology R6 class
#' @description
#' This object include the main caracteristics to get into a biological ontology
#' such as Gene Ontontology. With the object, you should be able to get the Gene
#' Ontology term information: name, depth, information content, and taxonomy relations.
#'
ontology <- R6Class("ontology", public = list(
  #' @field ids
  #' Character vector including the ids of a given ontology.
  ids= NULL,
  #' @field alternativeIDs
  #' List of possible alternative ids for the ontology ids.
  alternativeIDs = NULL,
  #' @description To create a new instance of this [ontology][R6::R6Class] class.
  #'
  #' @param ontologyList
  #'   A list of three elements:\cr
  #'   \itemize{
  #'   \item{}{ontologyList$name include a vector of ids of an ontology (e.g. GO:0008150
  #'   is a id in the Gene Ontology).}
  #'   \item{}{ontologyList$termOBJ include a list of term information (name, depth, children,
  #'   parents, ancestors, descendants, ...).}
  #'   \item{}{ontologyList$alternativeIds includes a list of terms and their alternative id.}
  #'
  #'   }
  #'   This list is generated by the [ontologyReader::reader()] method.
  initialize = function(ontologyList) {
    stopifnot(length(ontologyList) == 3)
    stopifnot(typeof(ontologyList)=="list")
    private$termobj <- ontologyList$termOBJ
    self$alternativeIDs <- ontologyList$alternativeIDs
    private$ics <- computegoUIC(ontologyList$termOBJ,ontologyList$name)
    self$ids <- ontologyList$name
    invisible(self)
  },
  #' @description
  #' Print this [ontology][R6::R6Class] class.
  #'
  print = function() {
    cat("ontoClass: \n")
    cat("  Number of onto terms: ", length(self$ids), "\n", sep = "")
    invisible(self)
  },
  #' @description
  #' To extract the children of a given term.
  #'
  #' @param term term id character.\cr
  #' @return Ontology id children vector of the give term.
  children = function(term){
    return(self$ids[private$termobj[[term]]$children])
  },
  #' @description
  #' To extract the parents of a given term.
  #'
  #' @param term term id character.\cr
  #' @return Ontology id parents vector of the give term.
  parents = function(term){
    return(self$ids[private$termobj[[term]]$parents])
  },
  #' @description
  #' To extract the ancestors of a given term.
  #'
  #' @param term term id character.\cr
  #' @return Ontology id ancestors vector of the give term.
  ancestors = function(term){
    return(self$ids[private$termobj[[term]]$ancestors])
  },
  #' @description
  #' To extract the descendants of a given term.
  #'
  #' @param term term id character.\cr
  #' @return Ontology id descendants vector of the give term.
  descendants = function(term){
    return(self$ids[private$termobj[[term]]$descendants])
  },
  #' @description
  #' To extract depth position (longest path from root) of a given term.
  #'
  #' @param term term id character.\cr
  #' @return term depth position.
  depth = function(term) {
    return(private$termobj$depth)
  },
  #' @description
  #' To extract the information content (IC) presented by Mazandu and Mulder 2013.
  #'
  #' @param term term id character.\cr
  #' @return IC value of the given term.
  ic = function(term) {
    return(private$ics[which(self$ids==term)])
  },
  #' @description
  #' To extract the top term associated to the given term.
  #'
  #' @param term term id character.\cr
  #' @return top term.
  top=function(term){
    return(private$termobj$top)
  },
  #' @description
  #' To extract term name.
  #'
  #' @param term term id character.\cr
  #' @return term name.
  name=function(term){
    return(private$termobj$name)
  }
),
private = list(
  termobj = NULL,
  ics = NULL
)
)
