# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computegoUIC <- function(ontology, ids) {
    .Call('_ontologyReader_computegoUIC', PACKAGE = 'ontologyReader', ontology, ids)
}

reader <- function(go_file) {
    .Call('_ontologyReader_reader', PACKAGE = 'ontologyReader', go_file)
}

gs2 <- function(setOfGenes, annotation, ontology) {
    .Call('_ontologyReader_gs2', PACKAGE = 'ontologyReader', setOfGenes, annotation, ontology)
}

